### ISSUE TITLE
GeSuit Spawns - Kicked off Server

### ISSUE THREAD

**Issue by ChrisWard316** [AddstarMC/geSuit#128]
Another issue with new players joining the server for the first time

Lets say i have a hub and 3 servers, each server has gesuitspawns and a new player joins them by doing server <name> they end up getting dc'd instantly if not joined before and once u do /server <name> you end up in some wall or in the floor usually around 5 blocks of the actual /setworldspawn and /setserverspawn but when in the wall you can type /spawn /ws /ss and you actually go to the spawn that is set. I have no idea maybe its related to my other issue but there is no errors in the console.

https://pastebin.com/raw/sZBvf6nS
https://pastebin.com/raw/FXx3Q6qC

I have narrowed it down to this plugin as i have removed every other plugin and it's still doing it

waterfall - 346
Paper 322
gesuit #199

This issue has been happening for months - players telling me they are spawning in walls and such and i've only just had the time to send in a report about it.

**Comment by Narimm** [comment]
@ChrisWard316 is this resolved ?  We did just add a patch that helps with Teleport issues...

**Comment by addstar** [comment]
I'm guessing this is likely a fight between Essentials and geSuit both trying to handle "first time join"?
