### ISSUE TITLE
Fetch old usernames on first join to show in /namehistory.

### ISSUE THREAD

**Issue by Absentee23** [AddstarMC/geSuit#14]
Mojang added an web/json API to lookup old usernames. This could allow geSuit to lookup these old names when a new player joins, and add them to the tracking database for **/namehistory** to show them even though they've never joined with those names. It gives dates for when they changed the name but I think it'd be best to just use the date of first join to prevent any confusion as to when someone actually first joined.

http://wiki.vg/Mojang_API#UUID_-.3E_Name_history

**Comment by addstar** [comment]
Yet another good idea, thanks @Absentee23!
Will look into this when I get some time :+1:
