### ISSUE TITLE
Portals deleted after restart

### ISSUE THREAD

**Issue by Blackyvk** [AddstarMC/geSuit#32]
I know you rarely restart your bungeecord server, but we have a script that restart the server everyday.

Sometimes portals get deleted for unknown reasons, there are no errors, they just dissapear... i dont know if they are deleted from the sql I didnt check the day before, but today they werent in the sql.

Also when I tried to place a /setproxyspawn (i already had one but decided to change it) it didnt update, i had to manually delete it from the sql db to add it again. 

Maybe a solution could be never restart bungeecord, but i think it should be looked at.I have months with this issue, almost everyday I have to recreate portals,I think warps arent affected.

**Comment by Narimm** [comment]
I suspect if you are not getting ANY error messages in the server logs on restart then you may want to look at the MYSQL logs to assess what SQL is getting passed in to delete your portals

http://stackoverflow.com/questions/303994/log-all-queries-in-mysql

If GeSuit itself is runng a query to delete your portals on startup this will show it....as it will show anything else that affects the DB.

before we can fix this bug we need to understand what is causing it

**Comment by Narimm** [comment]
As you have not responded I am closing this issue.
