### ISSUE TITLE
UUID value incompatiblity

### ISSUE THREAD

**Issue by epicbastion** [AddstarMC/geSuit#38]
Is there anyway to fix the format of the uuid to be compatible with nearly every other plugin?

gesuit's uuid
645e0fe3d2aa42f3a1146163cf611b9d

pex and nearly everyone else, essentials, minecraft etc.
b552e857-3f40-4f20-a338-5cf5d32eaa1e

Thanks, if this could be done it would make mysql queries so much easier.

**Comment by Narimm** [comment]
I believe this has been corrected in the redis branch (which is our current major redevelopment branch)  It wont be fixed in our master branch as this will be defunct once we move to redis.
