### ISSUE TITLE
Errors when converting bungeesuite database to geSuit

### ISSUE THREAD

**Issue by ospa555** [AddstarMC/geSuit#39]
I have these errors when converting bungeesuite database to geSuit:
http://hastebin.com/xatisahuvo.avrasm
I'm using the latest build in your Jenkins repository of geSuit and 2.2.3 Yamler.

**Comment by HeroCC** [comment]
The problem here is that you have a large amount of platers, and geSuite is making too many requests [see here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes. Try spacing out your conversion tries, or make geSuite ask for more players (up to 100 per request IIRC) per request.

**Comment by ospa555** [comment]
¿Another question is conversion compatible with offline mode?

**Comment by Narimm** [comment]
We dont really support offline mode, to convert a player geSuit needs to retrieve the players UUID from Mojang - if that player is not registered they are going to cause errors and they will not convert. Also github issues is not a support forum.  The plugins we work on are provided as is.  If you believe there to be  bug in the code please feel free to reopen the issue.
