### ISSUE TITLE
Support Yamler 2.3.0+

### ISSUE THREAD

**Issue by HeroCC** [AddstarMC/geSuit#40]
Yamler is now version 2.3.0, and as far as I can tell build 59 of Yamler is 2.2, and is out of date. The link to the cube-space jenkins is down, and the new [MD-5 repo](http://ci.md-5.net/job/Yamler/) reorders the build numbers. It would be best to support the latest Yamler, as many other plugins are incompatible with older versions. Is there any way to update the geSuite plugins to support the latest Yamler? Thanks!

**Comment by Narimm** [comment]
Thanks for the request we will need to assess the impact of this change to our server setup.  Please bear with us.

**Comment by HeroCC** [comment]
Ok, no problem!
