### ISSUE TITLE
Gesuit will work fine with offline server support?

### ISSUE THREAD

**Issue by xion87** [AddstarMC/geSuit#43]
i want know if this version of gesuit work fine now with offline server and if somesone using it, i already using a normal gesuit, and i want know if now it work fine...

**Comment by HeroCC** [comment]
geSuite doesn't officially support Offline Mode, see issue #39

**Comment by xion87** [comment]
:gonna cri:

**Comment by HeroCC** [comment]
It doesn't support it _officially_ but there is an option called OverwriteUUID, and the comment above it says it is for Offline mode. I have never tested it, but you are free to try if you like

**Comment by Narimm** [comment]
This isnt a support forum
