### ISSUE TITLE
Setting Enabled to false in bans.yml seems to have no effect

### ISSUE THREAD

**Issue by Dominic001** [AddstarMC/geSuit#50]
I have a different ban plugin on my server; however gesuit checks if there is a gesuit-ban database-table, (Which I have removed) and throws an error every time a player visits the server; even if I have disabled the gesuit-ban module in the ban.yml config.

**Comment by Narimm** [comment]
To be fair I think when you state you using an alternate plugin for something that causes a conflict its probably unlikely we are going to investigate very hard.  I would suggest you paste the error in a pastebin and paste your list of plugins on bungee and the spigot servers.  I am going to close the issue for now you can reopen it when we have those pieces of information AND they show a problem with geSuit not a plugin conflict.

**Comment by Narimm** [comment]
Marked close as need further info
