### ISSUE TITLE
GeoIP ShowCity: true --> "IP resolves to N/A"

### ISSUE THREAD

**Issue by helptiger** [AddstarMC/geSuit#57]
When enable GeoIP ShowCity Option I always get a "IP resolves to N/A". Is it working for you?

**Comment by alchemistmatt** [comment]
The GeoIPCity.dat file should be auto-downloaded if `ShowCity` is true and if `DownloadIfMissing` is true.
The source URL is specified by `CityDownloadURL`.  If the .dat file is not auto-downloading, you can try manually downloading from
http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz and then unzipping and placing in the `plugins/geSuit` folder with name `GeoIPCity.dat`

**Comment by helptiger** [comment]
hi, the file is already there, settings also
![screenshot 2016-04-01 at 10 36 27 pm](https://cloud.githubusercontent.com/assets/10258902/14219392/53d08a9e-f85a-11e5-8b65-cbb8bf64c2d0.png)

![screenshot 2016-04-01 at 10 39 25 pm](https://cloud.githubusercontent.com/assets/10258902/14219444/9f6856ee-f85a-11e5-9b71-db44bf1be8dc.png)

**Comment by alchemistmatt** [comment]
File permissions?  Hard to say what the issue is.  Yes, we see location names (not just IPs) for many of our players.  There is a subset of people for whom we only see the IP because the IP is not present in the .DAT file

**Comment by helptiger** [comment]
Essentials EssentialsXGeoIP-2.0.1 shows City, same Database!
/eseen Player

**Comment by helptiger** [comment]
with   ShowCity: false
![screenshot 2016-04-01 at 11 44 57 pm](https://cloud.githubusercontent.com/assets/10258902/14220960/ca62e9dc-f863-11e5-9695-6f11e60a2d71.png)

**Comment by helptiger** [comment]
enabled again and restarting bc it works! hope it was no april fool
![screenshot 2016-04-02 at 09 52 54 am](https://cloud.githubusercontent.com/assets/10258902/14225149/b97ac108-f8b8-11e5-9db4-3077553a971f.png)
