### ISSUE TITLE
Database schema changed?  Can't login after 1.9.2 update

### ISSUE THREAD

**Issue by SullyTheUnusual** [AddstarMC/geSuit#58]
Getting this in BungeeCord when trying to login:  http://hastebin.com/ayimisarod.profile

**Comment by alchemistmatt** [comment]
This is the current schema for the bans table in the gesuit database:
```SQL
 CREATE TABLE `bans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banned_playername` varchar(100) DEFAULT NULL,
  `banned_uuid` varchar(100) DEFAULT NULL,
  `banned_ip` varchar(15) DEFAULT NULL,
  `banned_by` varchar(100) DEFAULT NULL,
  `reason` text,
  `type` varchar(100) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `banned_on` datetime NOT NULL,
  `banned_until` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `banned_playername` (`banned_playername`),
  KEY `banned_uuid` (`banned_uuid`),
  KEY `banned_ip` (`banned_ip`)
)
```

**Comment by SullyTheUnusual** [comment]
Thanks for that info, but I guess I'm looking for a way to update the database schema without losing all my current data.  And it's not just the bans table that has changed, players and warps has new columns too.  It would be nice if there were instructions on how to update from 1.8 to 1.9 without having to start with a fresh database.

**Comment by alchemistmatt** [comment]
To be honest I don't know when the schema was changed, but it wasn't any time recently (and was not related to the 1.9 update). To add a column to the table, you use ALTER TABLE.  This should work:
```SQL
ALTER TABLE bans ADD COLUMN `active` tinyint(1) NOT NULL DEFAULT '0' AFTER `type`;
```
Or use this to just add the column on the far right of the table:
```SQL
ALTER TABLE bans ADD COLUMN `active` tinyint(1) NOT NULL DEFAULT '0';
```

See also http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

**Comment by SullyTheUnusual** [comment]
Thanks, I was already playing with commands to do this, but ran into trouble when needing the "firstonline" column in the players table.  Here's what I had to do:

ALTER TABLE bans ADD COLUMN active tinyint(1) NOT NULL DEFAULT '0' AFTER type;
ALTER TABLE players ADD COLUMN newspawn tinyint(1) DEFAULT '0' AFTER tps;
ALTER TABLE players ADD COLUMN firstonline DATETIME NOT NULL DEFAULT '2016-01-01 12:00:00' AFTER uuid;

I had to put a date in to get it to work, it wouldn't let me login if it was "0000-00-00 00:00:00".

**Comment by addstar** [comment]
Glad you managed to get it working again :+1: 
Closing issue.
