### ISSUE TITLE
EssentialsX vs. gesuit /seen command...

### ISSUE THREAD

**Issue by NoHoPeLess** [AddstarMC/geSuit#62]
Hello we use EssentialsX and gesuit, we would use the seen command from gesuit (not from essentials) and it seems to be impossible...? Have anyone an idea how we can do this? Or is there something wrong (bug)?

**Comment by Narimm** [comment]
/gesuit:seen would run the gesuit version.  Then all you need to do is create an alias using something like commandhelper

**Comment by NoHoPeLess** [comment]
with /gesuit:seen nothing happend...
