### ISSUE TITLE
seen command / perms and commands...

### ISSUE THREAD

**Issue by NoHoPeLess** [AddstarMC/geSuit#63]
First of all the seen command does not work at all...

/seen
/gesuit:seen

dont work... it says the command ist unknown..

We use essentialsX but we would use the gesuit command for this... or must be the bungeechat installed? (we use chatcontrol pro)

2nd: Is there any information/list about all available perms/commands for the gesuit ? i dont find any for this...

thanks for all!

**Comment by addstar** [comment]
Hello,

1) The `/seen` command is implemented on the BungeeCord plugin (`geSuit.jar`) so the command will only work when run on the BungeeCord console or in-game.

2) There is no updated documentation for our fork, but if you read the `plugin.yml` inside each jar, it will show you some of the permissions. Also you can refer to https://www.spigotmc.org/resources/gesuit.392/ for information from the official developer.

**Comment by NoHoPeLess** [comment]
Thank you , i solved it for myself but anyways thanks
