### ISSUE TITLE
Warp list not displaying

### ISSUE THREAD

**Issue by CKGAR** [AddstarMC/geSuit#64]
Hi, 

When running the command ./warp, the list of warps doesn't show. This is what appears in the Bungee server's console:

`

Send
29.12 17:37:30 [Server] INFO at java.lang.Thread.run(Unknown Source)
29.12 17:37:30 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
29.12 17:37:30 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
29.12 17:37:30 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
29.12 17:37:30 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
29.12 17:37:30 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
29.12 17:37:30 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
29.12 17:37:30 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:61)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:228)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
29.12 17:37:30 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
29.12 17:37:30 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source)
29.12 17:37:30 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
29.12 17:37:30 [Server] INFO at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
29.12 17:37:30 [Server] INFO at net.cubespace.geSuit.listeners.WarpsMessageListener.receivePluginMessage(WarpsMessageListener.java:51)
29.12 17:37:30 [Server] INFO at net.cubespace.geSuit.managers.WarpsManager.getWarpsList(WarpsManager.java:89)
29.12 17:37:30 [Server] INFO java.lang.NullPointerException
29.12 17:37:30 [Server] INFO WARNING: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@3bc7e53a, receiver=Lil_Shadow15), cancelled=true, tag=geSuitWarps) to listener net.cubespace.geSuit.listeners.WarpsMessageListener@60fa3495
29.12 17:37:30 [Server] SEVERE Dec 29, 2016 5:37:30 PM net.md_5.bungee.event.EventBus post`

**Comment by addstar** [comment]
Hi,

Can you check if there's any errors prior to this one? Try doing a fresh restart and looking for any other error before this one.

When did this error first happen? Was it only after an upgrade of something? Was it working properly before this or is this a new installation?

Also can you tell me which build versions you are running (geSuit + geSuitWarps) and also the build of spigot+bubgee?

**Comment by CKGAR** [comment]
There are no errors prior to this, only this one. It is triggered by running ./warp. 

I am pretty sure this started happening after updating to 1.11.2 and BungeeCord build b728aea. I can't remember completely, but I think it worked on 1.11. 

Build version(s):
Spigot: This server is running CraftBukkit version git-Spigot-7d78b81-70bc70b (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Bungee: This server is running BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:6104354:1217 by md_5

geSuit: Build #114 (Off of http://jenkins.addstar.com.au/)

geSuitWarps: Build #10 (Off of http://jenkins.addstar.com.au/)

**Comment by addstar** [comment]
@CKGAR Thanks for the thorough info, very helpful!

I had a look into this and I'm not sure this is caused by the 1.11.2 upgrade. It's possible that there was some other change around the same time that is causing this.

Looking at the line causing the NPE, I can only think of two possibilities:
1. You have some erroneous data in your "warps" table? Check the contents of this and look for any bad rows, possibly with empty names or names referring to servers that no longer exist.
2. There's something unusual about your bungee config or player connection. Can you confirm that you ran this command as a player and the player was connected via BungeeCord to a properly configured spigot server?

**Comment by CKGAR** [comment]
Whoops! Yeah, it seems that I had a warp to an old server still in that table. I thought I had deleted them all but apparently not. Everything is working as normal for now. Sorry for troubling you for such a small thing! Thank you again for maintaining geSuit, I'm not sure how many people still use it but it simplifies how I run things on my network.
