### ISSUE TITLE
don't works every times

### ISSUE THREAD

**Issue by tryolivier** [AddstarMC/geSuit#66]
hello :)

 thanks to updated gesuit (http://jenkins.addstar.com.au/job/geSuit/)

 but there are big bug

 I start the proxy but 3 times on 5 the proxy can't load

 02:27:23 [INFOS] Starting geSuit
 02:27:23 [INFOS] Initialising Managers
 and thats all it don't start

 Initialising Managers don't works every times

 can you check that please ??

 thanks

**Comment by Narimm** [comment]
Sorry not enough infor cant replicate..

**Comment by tryolivier** [comment]
:/

**Comment by Narimm** [comment]
With no stacktrace I cant debug it. For all I can tell it may be other bungee plugins causing the issue..

.I can say  we dont have this issue... and we restart proxy fortnightly and its never been an issue.

**Comment by tryolivier** [comment]
ok thanks to had a look ;)
