### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by SeruhioX** [AddstarMC/geSuit#68]
1- For a long time, for some reason the log is full of errors when a user teleports.
Also "/tpall" doesn't work.
This error occurs constantly.
 
https://pastebin.com/6kWsr2TY
https://pastebin.com/MAudrk61
 
I have deleted my database several times to see if it could be a bug in it, but these errors still occur, my servers are in version 1.12
The plugins I use in bungeecord are: BungeeTabListPlus, DeluxeChat, ExecuteEverywhere, geSuit, ServerListPlus, Yamler-Bungee.
 
2- Many times when someone has lag, when he stops lagging he can't use the commands of this plugin, he has to leave the server and re-enter.
 
3- When a user enters the server for the first time, he can't use the commands of this plugin, after leaving and then entering again he can use them normally.
 
4- There are times that users enter with a domain ip and several errors occur, also in the database the ip gets cut instead of converting it to a normal ip
 
https://pastebin.com/vU4pbDLT
 
5- Maybe I'm mistaken with how warps work, but server warps should not be usable from a different server, since it makes it no different to a global warp.
 
Server warps should be able to replicate the name and be independent of other servers (as if it were a server plugin, such as essentials)
 
Maybe I'm making a mistake in this, that's why I ask.

**Comment by SeDark** [comment]
Some news?

**Comment by Narimm** [comment]
Can we confirm this is still occuring in recent builds?

**Comment by Narimm** [comment]
Closed as no feedback
