### ISSUE TITLE
Exception for Cracked players

### ISSUE THREAD

**Issue by Artuto** [AddstarMC/geSuit#80]
Basically a new cracked player joined today, and geSuit had a bad time with it. 

https://haste.kantenkugel.com/eluraxafes.cs

When they tried to warp or teleport the plugin didnt respond for them or just said the user was offline. Please fix ASAP.

**Comment by addstar** [comment]
Sorry, but we don't support cracked servers, nor do we have any interest supporting them. We only support `online_mode: true` BungeeCord servers. You could try enabling `OverwriteUUID: true` in the gesuit config but I don't even know if this works now. We forked geSuit from the original author and maintain it for our own server network.

If this doesn't help, please feel free to fork the project and make whatever changes you need. We will not provide support for cracked servers.

**Comment by Artuto** [comment]
You should do at least a way to disable name tracking, as its useless with some websites like namemc IMO
